export const genZExamples = [
  "no cap fr fr this slaps different bestie",
  "bestie is straight bussin rn ngl sheesh",
  "ong this tea is living rent free in my head rn",
  "periodt bestie you ate that and left no crumbs",
  "its giving main character energy fr fr",
  "lowkey sus but go off king periodt",
  "finna be real with you chief no cap",
  "deadass cant even rn bestie im shook",
  "respectfully, you understood the assignment and ate",
  "ngl this fit be bussin fr fr no cap",
  "ion even know why im so pressed rn bestie",
  "ong bestie this slaps different no printer",
  "the way you ate and left no crumbs, periodt",
  "im literally obsessed with this rn no cap",
  "bestie spilled the tea and im living for it fr",
  "caught in 4k acting real sus rn ngl",
  "this hits different fr fr im deceased",
  "living my best life rn no cap bestie",
  "straight bussin fr fr on god no cap",
  "material gworl energy periodt and thats on what"
];

export const englishExamples = [
  "This is absolutely amazing and perfect",
  "I'm being completely honest with you right now",
  "That's very suspicious behavior honestly",
  "This is the greatest thing I've ever seen",
  "I'm really excited about this new project",
  "You're absolutely right about everything",
  "I can't believe this is actually happening",
  "This is constantly on my mind lately",
  "You did an excellent job with this work",
  "I'm seriously impressed with your effort",
  "I don't understand why I'm so upset",
  "This is definitely the best thing ever",
  "The way you handled that was perfect",
  "I'm really obsessed with this right now",
  "My friend shared some interesting gossip",
  "I caught you doing something suspicious",
  "This feels really special and unique",
  "I'm really enjoying life right now",
  "This is absolutely perfect in every way",
  "You have such amazing confidence"
];